### ISSUE TITLE
[Mass Image Compressor 3.2.2] Compress Images of Directory

### ISSUE THREAD

**Issue by albert88nt** [FireEmerald/MassImageCompressor#1]
After updating to the latest version 3.2.2 on Windows 11(Version: 23H2, OS build: 22631.4317) i am getting this error:

```
Unhandled exception has occured in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately.

Path cannot be empty, string or all whitespace.
Parameter name: path

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentException: Path cannot be the empty string or all whitespace.
Parameter name: path
   at System.IO.Directory.GetParent(String path)
   at NeoFoton.MainUI.btnSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9277.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
Image Compressor
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Mass%20Image%20Compressor%20V.3/Image%20Compressor.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9251.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9261.0 built by: NET481REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
NeoFotonCommon
    Assembly Version: 3.2.0.0
    Win32 Version: 3.2.0.0
    CodeBase: file:///C:/Program%20Files%20(x86)/Mass%20Image%20Compressor%20V.3/NeoFotonCommon.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9277.0 built by: NET481REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.9032.0 built by: NET481REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by yogendrasinh** [comment]
Upload a screenshot please. Where did you get your binaries from? Here (github) or https://sourceforge.net/projects/icompress/ ?

**Comment by albert88nt** [comment]
![2024-10-28 20_37_50- Mass Image Compressor 3 2  Compress Images of Directory](https://github.com/user-attachments/assets/568a0b33-4500-46e7-bb0a-b600c8382632)
I got the binaries from Sourceforge

**Comment by yogendrasinh** [comment]
If so, I coded that bug :( This is because the input directory is not selected. If you have just installed the software, close the software and restart it. I will stop auto-start feature (post installation) in next release.

**Comment by albert88nt** [comment]
Yes, it shows up when i am trying to select a folder. I have installed the software a couple of months ago. Now it's not working. I migh have to install an older version

**Comment by yogendrasinh** [comment]
Doesn't look like you selected the input directory.

**Comment by albert88nt** [comment]
Well, i can't since that error shows when i click the 3 dots

**Comment by yogendrasinh** [comment]
Thanks for the info. I will try to fix it in next release. Sorry that you need to suffer for my oversight. 
As a work around, you can copy the whole path there. You can see how to do it here: https://www.youtube.com/watch?v=YV79oATsIRE

**Comment by yogendrasinh** [comment]
Also, didn't "drag & drop" work for you?

**Comment by albert88nt** [comment]
Drag and drop works fine. I have also noticed that after update, the Window and text(from buttons) is way bigger

**Comment by yogendrasinh** [comment]
It's simply because I am about to get my reading glasses so I make everything big nowadays. Does it feel odd/bad/ugly? I am currently working on https://apps.apple.com/app/id6670366523 once I am done there, I will be back on MIC for Windows so all feedback are welcome.

**Comment by albert88nt** [comment]
For me, it looks bad...compared with the old versions. It maybe help of users can zoom in/out as they want

**Comment by yogendrasinh** [comment]
This is fixed in latest version. Please let me know if you face any other issue.
https://sourceforge.net/projects/icompress
